### ISSUE TITLE
Warning when compiling for arm64

### ISSUE THREAD

**Issue by CocoaPriest** [zrxq/UIView-EasingFunctions#7]
`- (void)setEasingFunction:(ViewEasingFunctionPointerType)function forKeyPath:(NSString *)keyPath`

__warning_: incompatible pointer types sending 'float (float)' to parameter of type 'ViewEasingFunctionPointerType' (aka 'CGFloat (*)(CGFloat)')_

**Comment by zrxq** [comment]
My best guess is that you are trying to pass an easing function from AHEasing. Unfortunately, AHEasing uses it's own type `AHFloat` (instead of `CGFloat`) defined as follows:

``` obj-c
#ifdef AH_EASING_USE_DBL_PRECIS
#define AHFloat double
#else
#define AHFloat float
#endif
```

As you can see, unlike `CGFloat` it uses `float` regardless of the architecture, unless `AH_EASING_USE_DBL_PRECIS` is defined. To deal with this you could either configure your 64-bit target to define `AH_EASING_USE_DBL_PRECIS` or put something like this

``` obj-c
#if __LP64__
#define AH_EASING_USE_DBL_PRECIS
#endif
```

somewhere before importing `AHEasing.h` (`App-Prefix.pch` sounds about right).
